default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
    build_app(
        scheme: "Runner",
        archive_path: "./build/Runner.xcarchive",
        export_method: "development",
        output_directory: "./build/Runner"
    )
    lane :upload_to_firebase do
      firebase_app_distribution(
          app: "1:412823237422:ios:8947f503f8cb2000fb40bf",
          testers: "hieu.trantrung1204@gmail.com, inspireui.build@gmail.com",
          release_notes: "Initial test version of the app",
          firebase_cli_path: "/usr/local/bin/firebase",
          ipa_path: "./build/Runner/Runner.ipa"
      )
    end
   
end
